### PR TITLE
HSDO-676 Paragraph Styles

### PR DESCRIPTION
**Pull request by josephgknox**

### CODE REVIEW

**Comment by josephgknox** [comment]
@pookmish two things that I could use you help with:

1. wrapping the WYSIWYG title in an H2
2. adding the more-link class to links in the hero overlay

**Comment by pookmish** [comment]
wysiwgy title should be in h2. i added the more-link class

**Comment by josephgknox** [comment]
Woot! We're looking good. I'm not seeing the more-link in the hero overlay, but the WYSIWYG headers are back.

**Comment by josephgknox** [comment]
@pookmish TY for the feedback !!

**Comment by pookmish** [comment]
I reverted the feature and the more-link is now there. any more changes on your end?

**Comment by josephgknox** [comment]
All good!

joe

**Pull request merged**
