### PR TITLE
EARTH-280: Left center right variant options for feature blocks

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Adds new variants to section feature blocks paragraph type

# Needed By (Date)
- Sometime before end of the sprint so I can post it for Nick to review.

# Steps to Test

1. Check out this branch and EARTH-280 in stanford_components
2. Revert `drush features-import stanford_paragraph_feat_blocks -y`
3. Edit the home page and choose a few variants from the feature blocks p-type
4. Review front end for placement

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by pookmish — CHANGES_REQUESTED** [review]
I'm not getting much of a difference when i edit the featured blocks. The section header text continues to stay to the left of the blocks. It sometimes goes text aligned centered but thats all

**Comment by sherakama** [comment]
@pookmish,

Are you sure you had the correct branch of stanford_components checked out as well?
Cleared the cache?

I'll pull and review as well.

**Comment by sherakama** [comment]
RE: https://cl.ly/3Q3V0v3M2b3L
RE: https://cl.ly/1Z0N0O0a0j3U

**Comment by pookmish** [comment]
Ahh i must have typed in the wrong branch for the components

**Review by pookmish — APPROVED** [review]

**Pull request merged**
