### PR TITLE
7.x-1.5

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Tag and release

```
# What (Changelog)
- Use Vimeo and Youtube's APIs when loading and auto-playing a video.

# So what
- Improved javascript API usage on video loading

# Now what
- Nothing

# New Requirements and Risks (Changelog)
- None

# Diff
- https://github.com/SU-SWS/stanford_paragraph_types/compare/7.x-1.4...7.x-1.5
```

### CODE REVIEW

**Comment by jbickar** [comment]
@sherakama do we want a version # in the `README`?

**Comment by sherakama** [comment]
We stopped doing that as it kept falling out of sync.

**Comment by jbickar** [comment]
In READMEs for submodules, yes. But the parent README too?

**Comment by sherakama** [comment]
Jah, there are all sorts of ways to see what the version number is. The version in any of the README.md files get forgotten about too often.

**Comment by jbickar** [comment]
_FINE_

**Review by jbickar — APPROVED** [review]

**Pull request merged**
