### PR TITLE
Dependency Fixes

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Patches up missing dependencies so these can be used in Vanilla Drupal

# Needed By (Date)
- Not that urgent

# Urgency
- Not that urgent

# Steps to Test

1. Freshly install a copy of Drupal `drush si standard -y`
2. Enable a single paragraph type with `drush en modulename -y`
3. Validate it enabled.
4. Repeat for each.

^ That was a lot of work so you might want to script it.

# Affected Projects or Products
- Just Earth so far

# Associated Issues and/or People
- Thanks Mike.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by pookmish — CHANGES_REQUESTED** [review]
I'm still having some trouble enabling some.
I enabled them one after another and got the following errors:
- stanford_paragraph_buttons: `Configuration objects provided by <em>stanford_paragraph_buttons</em> have unmet dependencies: <em>core.entity_view_display.paragraph.stanford_buttons.default(field_formatter_class)</em>`
- stanford_paragraph_slide `Attempt to save a configuration entity 'component_film_card' with UUID '' when this UUID is already used for 'stanford_paragraph_callout_card_50x50'`
- stanford_paragraph_callout_filmstrip: `Configuration objects provided by <em>stanford_paragraph_callout_filmstrip</em> have unmet dependencies: <em>field.field.paragraph.stanford_callout_filmstrip.field_p_callout_film_cards (paragraphs.paragraphs_type.stanford_slide)</em>`
- stanford_paragraph_callout_text: `Configuration objects (field.storage.paragraph.field_p_wysiwyg) provided by stanford_paragraph_callout_text already exist in active configuration`
- stanford_paragraph_filmstrip: `onfiguration objects provided by <em>stanford_paragraph_filmstrip</em> have unmet dependencies: <em>field.field.paragraph.stanford_paragraph_filmstrip.field_p_filmstrip_slide (paragraphs.paragraphs_type.stanford_slide)</em>`

**Comment by sherakama** [comment]
Thanks, I'll hop on to these now.

**Comment by sherakama** [comment]
@pookmish Ready for another review. 

I had to change the field name on the callout_text from field_p_wysiwyg to field_p_callout_wysiwyg.

We will likely need an upgrade path :S

**Comment by pookmish** [comment]
Modules can now be enabled. I enabled them one after another and randomized the order several times. it still worked. I'll build out a migration for the field data

**Review by sherakama — COMMENTED** [review]
@pookmish 
Nice work on the upgrade path for the field. It works great. This PR is approved. Please merge.

**Pull request merged**
