### PR TITLE
EARTH-295 Section Header Paragraph Type

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Section Header Paragraph Type

# Needed By (Date)
- EOS

# Urgency
- Low

# Steps to Test

1. Checkout branch
2. `drush en stanford_paragraph_section_header -y`
3. create complex page with "Section Header" type
4. Verify it displays correctly.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — CHANGES_REQUESTED** [review]
Please expose the display variants as options to the content author. 

Also, update the template to add the centered component variant so that it doesn't get slammed to the left edge of the screen.

**Comment by pookmish** [comment]
Added fields to change variants. Currently the only one with any styles is the `is_centered` variant. the dash_under & is_featured do nothing right now.
Also added the centered container at https://github.com/SU-SWS/stanford_components/pull/57

**Comment by pookmish** [comment]
I'm guessing we didnt want to expose the container centering to the author though?

**Review by sherakama — APPROVED** [review]
This is good enough for now. We will have to review and revise all the different display options from the design comps. There is more work to be done on this component but this is good enough for the content author to use.

**Pull request merged**
